/**
 * Burger store
 * la boutique des burgers
 *
 * OpenAPI spec version: 1.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Nutriment } from './nutriment';

export interface BurgerDetail { 
    id?: number;
    name?: string;
    price?: number;
    image?: string;
    nutriscore?: string;
    nutriments?: Nutriment;
}